name: test
on:
  push
jobs:
  automated-scrape:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@main

      - name: Setup yt-dlp
        uses: AnimMouse/setup-yt-dlp@main

      - run: |
          sudo apt update
          sudo apt install tor
          sudo systemctl start tor --now
          sudo systemctl enable tor --now
          curl -fsSL https://deno.land/install.sh | sh
          while ! torsocks yt-dlp -f 140 NSIC3QVGzNE _ZNOLgM_518 mjqwTY9zjq4 5cq7y-OYxCY wrLJxZQUZqA ; do torsocks curl -s http://httpbin.org/ip ; sudo systemctl restart tor --now ; sleep 5s ; done && echo "Success!"

      - name: git stuff
        run: |
          git config --local user.email "action[bot]@github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "$(od -An -tx4 -w16 -N16 /dev/urandom | cut -c2- | tr '[:lower:]' '[:upper:]')"
          git push
