name: test
on:
  push
jobs:
  automated-scrape:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@main

      - name: run commands
        run: |
          #for i in $(cat genres.txt) ; do curl -s https://play.you.radio/station_name/$(echo $i | awk -F '---' '{print $1}') | awk 'NR==1 {$0="#EXTINF:-1," $0} 1' >> A-$(echo $i | awk -F '---' '{print $2}').txt ; curl -s https://play.you.radio/player_stream/$(echo $i | awk -F '---' '{print $1}') | xargs wget --max-redirect=0 -O /dev/null 2>&1 | grep 'Location' >> A-$(echo $i | awk -F '---' '{print $2}').txt ; echo -e "\n" >> A-$(echo $i | awk -F '---' '{print $2}').txt ; echo -e $i ; done
          npm install playwright
          node ./castbox.js

      - name: git stuff
        run: |
          git config --local user.email "action[bot]@github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "$(od -An -tx4 -w16 -N16 /dev/urandom | cut -c2- | tr '[:lower:]' '[:upper:]')"
          git push
