name: test
on:
  push
jobs:
  automated-scrape:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@main

      - name: run commands
        run: |
          for i in $(cat list.txt) ; do curl -s "https://api.tunein.com/profiles?fullTextSearch=true&query=$i&filter=s&ignoreProfileRedirect=true&ignoreCategoryRedirect=true&formats=mp3,aac,ogg,flash,html,hls,wma&partnerId=RadioTime&version=6.71&itemUrlScheme=secure&reqAttempt=1" --compressed -H 'User-Agent: Mozilla/5.0' -H 'Accept: application/json' > $i.json ; echo $i ; done

      - name: git stuff
        run: |
          git config --local user.email "action[bot]@github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "$(od -An -tx4 -w16 -N16 /dev/urandom | cut -c2- | tr '[:lower:]' '[:upper:]')"
          git push
