name: test
on:
  push
jobs:
  automated-scrape:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@main

      - uses: tor-actions/setup-tor@main
        with:
          daemon: true

      - uses: wangsijie/setup-v2ray@v1
        with:
          config-base64: ${{ https://raw.githubusercontent.com/voidr3aper-anon/GFW-slayer/refs/heads/main/configs/regional/iran/emergency-add-on-for-iran.json }}

      - name: Setup yt-dlp
        uses: AnimMouse/setup-yt-dlp@main
    
      - run: while ! yt-dlp --proxy socks5://127.0.0.1:1080/ --flat-playlist -s --print "id" "https://www.youtube.com/@AhmadZeidabadii" > ids.txt ; do sleep 5s ; done && echo "Success!"

      - name: git stuff
        run: |
          git config --local user.email "action[bot]@github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "$(od -An -tx4 -w16 -N16 /dev/urandom | cut -c2- | tr '[:lower:]' '[:upper:]')"
          git push
