name: test
on:
  push
jobs:
  automated-scrape:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@main

      - name: run commands
        run: |
          for i in $(cat streams.txt) ; do echo $i | awk -F '_____' '{print $2"___"$3}' | awk '{print "#EXTINF:-1,"$0}' >> output.txt ; curl -s 'https://opml.radiotime.com/Tune.ashx?id=$(echo $i | awk -F '_____' '{print $1}')&formats=mp3,aac,ogg,flash,html,hls,wma&version=6.71&itemUrlScheme=secure&render=json&reqAttempt=1' --compressed -H 'User-Agent: Mozilla/5.0' -H 'Accept: application/json' -H 'Referer: https://tunein.com/' | grep url | awk -F '"' '{print $4}' >> output.txt ; echo $i ; done

      - name: git stuff
        run: |
          git config --local user.email "action[bot]@github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "$(od -An -tx4 -w16 -N16 /dev/urandom | cut -c2- | tr '[:lower:]' '[:upper:]')"
          git push
