name: test
on:
  push
jobs:
  automated-scrape:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@main

      - name: run commands
        run: |
          sudo apt install tor -y
          sudo systemctl start tor
          sleep 10s
          for i in A-*.txt ; do for j in $(cat $i) ; do curl --socks5-hostname localhost:9050 -s https://www.allonlineradio.com/$j/ > mep1 ; cat mep1 | htmlq -t h2 | awk '{print "#EXTINF:-1,"$0}' >> A$i ; cat mep1 | grep "<source" | awk -F '"' '{print $2}' | sed 's/\;//g' | sed '/^$/d' | sed 's|?type=.mp3||g' >> A$i ; echo -e "$i - $j" ; done ; done
          sudo systemctl stop tor

      - name: git stuff
        run: |
          git config --local user.email "action[bot]@github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "$(od -An -tx4 -w16 -N16 /dev/urandom | cut -c2- | tr '[:lower:]' '[:upper:]')"
          git push
