name: test
on:
  push
jobs:
  automated-scrape:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@main

      - name: run commands
        run: |
          while read url; do curl -s "https://radionations.com$url" > mep1 && title=$(./htmlq -t h1 < mep1) && country=$(./htmlq -t "#main > section.station-hero > div:nth-child(2) > p" < mep1 | tr '\n' ' ' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' | tr -cd '[:alnum:] \n' | sed 's/  */ /g') && genre=$(./htmlq -t "#main > section.station-hero > div:nth-child(2) > div.meta-row > span:nth-child(2)" < mep1 | tr '\n' ' ' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' | tr -cd '[:alnum:] \n' | sed 's/  */ /g') && stream=$(./htmlq "#main > section.station-hero > div:nth-child(2) > div.station-actions > button.btn-play-large" < mep1 | grep -oP 'data-stream="\K[^"]*') && [ -n "$stream" ] && echo -e "#EXTINF:-1,$title\n$stream" >> "${country// /_}.m3u" && echo -e "#EXTINF:-1,$title\n$stream" >> "${genre// /_}.m3u"; done < stations.txt
          #node ./m3u-checker.js test_input/ test_output/ --quiet

      - name: git stuff
        run: |
          git config --local user.email "action[bot]@github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "$(od -An -tx4 -w16 -N16 /dev/urandom | cut -c2- | tr '[:lower:]' '[:upper:]')"
          git push
